import { BoxGeometry, Mesh, MeshStandardMaterial, Scene, Texture } from 'three';
import { expect, it, vi } from 'vitest';
import { CaptureMaterials } from '../src/ocean/CaptureMaterials';

// Importance: 98/100. Water captures must preserve live material changes and release their caches.
it('shares current material values and hooks, restores bindings, and releases disposed sources', () => {
  const materials = new CaptureMaterials();
  const source = new MeshStandardMaterial();
  const map = new Texture();
  source.map = map;
  source.onBeforeCompile = vi.fn();
  source.onBeforeRender = vi.fn();
  source.customProgramCacheKey = () => 'fog';
  const array = [source, source];
  const mesh = new Mesh(new BoxGeometry(), source);
  const multi = new Mesh(mesh.geometry, array);
  const scene = new Scene();
  scene.add(mesh, multi);
  materials.apply(scene);
  const capture = mesh.material;
  expect(capture).not.toBe(source);
  expect(capture.uuid).not.toBe(source.uuid);
  expect(multi.material).toEqual([capture, capture]);
  expect(capture.map).toBe(map);
  expect(capture.color).toBe(source.color);
  expect(capture.onBeforeCompile).toBe(source.onBeforeCompile);
  expect(capture.onBeforeRender).toBe(source.onBeforeRender);
  expect(capture.customProgramCacheKey()).toBe('fog');
  materials.restore();
  expect(mesh.material).toBe(source);
  expect(multi.material).toBe(array);
  source.opacity = 0.4;
  source.transparent = true;
  source.depthWrite = false;
  source.needsUpdate = true;
  materials.apply(scene);
  expect(mesh.material).toBe(capture);
  expect(capture.opacity).toBe(0.4);
  expect(capture.transparent).toBe(true);
  expect(capture.depthWrite).toBe(false);
  expect(capture.version).toBe(source.version);
  materials.restore();
  const disposed = vi.fn();
  capture.addEventListener('dispose', disposed);
  source.dispose();
  expect(disposed).toHaveBeenCalledTimes(1);
  materials.dispose();
  expect(disposed).toHaveBeenCalledTimes(1);
  mesh.geometry.dispose();
  map.dispose();
});
